const fs = require('fs');
let content = fs.readFileSync('src/items.ts', 'utf8');

const clothes = `
  // === CLOTHING (ОДЕЖДА) ===
  // HEAD
  beanie_black: {
    itemId: 'beanie_black',
    name: 'Black Beanie',
    nameRu: 'Черная шапка',
    category: 'clothing',
    maxStack: 1,
    icon: '🧢',
    description: 'A warm woolen black beanie.',
    descriptionRu: 'Теплая шерстяная черная шапка.',
    effects: {},
    weight: 0.1,
    usable: true,
  },
  cap_red: {
    itemId: 'cap_red',
    name: 'Red Cap',
    nameRu: 'Красная кепка',
    category: 'clothing',
    maxStack: 1,
    icon: '🧢',
    description: 'A simple red baseball cap. Protects from the sun.',
    descriptionRu: 'Простая красная бейсболка. Защищает от солнца.',
    effects: {},
    weight: 0.1,
    usable: true,
  },
  ushanka_hat: {
    itemId: 'ushanka_hat',
    name: 'Ushanka Hat',
    nameRu: 'Шапка-ушанка',
    category: 'clothing',
    maxStack: 1,
    icon: '🎩',
    description: 'Very warm fur hat for severe frosts.',
    descriptionRu: 'Очень теплая меховая шапка для суровых морозов.',
    effects: {},
    weight: 0.3,
    usable: true,
  },

  // FACE
  sunglasses: {
    itemId: 'sunglasses',
    name: 'Sunglasses',
    nameRu: 'Солнцезащитные очки',
    category: 'clothing',
    maxStack: 1,
    icon: '🕶️',
    description: 'Dark glasses to protect your eyes from bright light.',
    descriptionRu: 'Темные очки для защиты глаз от яркого света.',
    effects: {},
    weight: 0.05,
    usable: true,
  },
  scarf_blue: {
    itemId: 'scarf_blue',
    name: 'Blue Scarf',
    nameRu: 'Синий шарф',
    category: 'clothing',
    maxStack: 1,
    icon: '🧣',
    description: 'Knitted warm blue scarf.',
    descriptionRu: 'Вязаный теплый синий шарф.',
    effects: {},
    weight: 0.15,
    usable: true,
  },

  // UNDERWEAR
  tshirt_white: {
    itemId: 'tshirt_white',
    name: 'White T-Shirt',
    nameRu: 'Белая футболка',
    category: 'clothing',
    maxStack: 1,
    icon: '👕',
    description: 'Light breathable cotton t-shirt.',
    descriptionRu: 'Легкая дышащая хлопковая футболка.',
    effects: {},
    weight: 0.1,
    usable: true,
  },
  tshirt_black: {
    itemId: 'tshirt_black',
    name: 'Black T-Shirt',
    nameRu: 'Черная футболка',
    category: 'clothing',
    maxStack: 1,
    icon: '👕',
    description: 'Simple black cotton t-shirt.',
    descriptionRu: 'Простая черная хлопковая футболка.',
    effects: {},
    weight: 0.1,
    usable: true,
  },
  long_johns: {
    itemId: 'long_johns',
    name: 'Thermal Underwear',
    nameRu: 'Термобелье',
    category: 'clothing',
    maxStack: 1,
    icon: '🩲',
    description: 'Warm base layer for cold weather.',
    descriptionRu: 'Теплый базовый слой для холодной погоды.',
    effects: {},
    weight: 0.2,
    usable: true,
  },

  // SHIRTS
  sweater_blue: {
    itemId: 'sweater_blue',
    name: 'Blue Sweater',
    nameRu: 'Синяя кофта',
    category: 'clothing',
    maxStack: 1,
    icon: '🧥',
    description: 'Comfortable blue knitted sweater.',
    descriptionRu: 'Удобная синяя вязаная кофта.',
    effects: {},
    weight: 0.4,
    usable: true,
  },
  plaid_shirt: {
    itemId: 'plaid_shirt',
    name: 'Plaid Shirt',
    nameRu: 'Клетчатая рубашка',
    category: 'clothing',
    maxStack: 1,
    icon: '👔',
    description: 'Flannel plaid shirt. Classic.',
    descriptionRu: 'Фланелевая клетчатая рубашка. Классика.',
    effects: {},
    weight: 0.3,
    usable: true,
  },

  // JACKETS
  leather_jacket: {
    itemId: 'leather_jacket',
    name: 'Leather Jacket',
    nameRu: 'Кожаная куртка',
    category: 'clothing',
    maxStack: 1,
    icon: '🧥',
    description: 'Tough leather jacket. Good wind protection.',
    descriptionRu: 'Прочная кожаная куртка. Хорошо защищает от ветра.',
    effects: {},
    weight: 1.2,
    usable: true,
  },
  winter_jacket: {
    itemId: 'winter_jacket',
    name: 'Winter Down Jacket',
    nameRu: 'Зимний пуховик',
    category: 'clothing',
    maxStack: 1,
    icon: '🧥',
    description: 'Heavy insulated jacket for extreme cold.',
    descriptionRu: 'Тяжелая утепленная куртка для сильных морозов.',
    effects: {},
    weight: 1.5,
    usable: true,
  },
  raincoat_yellow: {
    itemId: 'raincoat_yellow',
    name: 'Yellow Raincoat',
    nameRu: 'Желтый дождевик',
    category: 'clothing',
    maxStack: 1,
    icon: '🧥',
    description: 'Waterproof raincoat. Keeps you dry but not very breathable.',
    descriptionRu: 'Водонепроницаемый плащ. Сохранит сухим, но почти не дышит.',
    effects: {},
    weight: 0.3,
    usable: true,
  },

  // LEGS
  jeans_blue: {
    itemId: 'jeans_blue',
    name: 'Blue Jeans',
    nameRu: 'Синие джинсы',
    category: 'clothing',
    maxStack: 1,
    icon: '👖',
    description: 'Classic durable denim jeans.',
    descriptionRu: 'Классические прочные джинсы.',
    effects: {},
    weight: 0.6,
    usable: true,
  },
  cargo_pants: {
    itemId: 'cargo_pants',
    name: 'Cargo Pants',
    nameRu: 'Штаны карго',
    category: 'clothing',
    maxStack: 1,
    icon: '👖',
    description: 'Practical pants with many pockets.',
    descriptionRu: 'Практичные штаны с множеством карманов.',
    effects: {},
    weight: 0.7,
    usable: true,
  },
  shorts_khaki: {
    itemId: 'shorts_khaki',
    name: 'Khaki Shorts',
    nameRu: 'Шорты хаки',
    category: 'clothing',
    maxStack: 1,
    icon: '🩳',
    description: 'Lightweight shorts for hot weather.',
    descriptionRu: 'Легкие шорты для жаркой погоды.',
    effects: {},
    weight: 0.2,
    usable: true,
  },

  // FEET
  sneakers_white: {
    itemId: 'sneakers_white',
    name: 'White Sneakers',
    nameRu: 'Белые кроссовки',
    category: 'clothing',
    maxStack: 1,
    icon: '👟',
    description: 'Comfortable sports shoes.',
    descriptionRu: 'Удобная спортивная обувь.',
    effects: {},
    weight: 0.5,
    usable: true,
  },
  work_boots: {
    itemId: 'work_boots',
    name: 'Work Boots',
    nameRu: 'Рабочие ботинки',
    category: 'clothing',
    maxStack: 1,
    icon: '👢',
    description: 'Heavy duty leather boots.',
    descriptionRu: 'Тяжелые кожаные рабочие ботинки.',
    effects: {},
    weight: 1.2,
    usable: true,
  },
  winter_boots: {
    itemId: 'winter_boots',
    name: 'Winter Boots',
    nameRu: 'Зимние ботинки',
    category: 'clothing',
    maxStack: 1,
    icon: '👢',
    description: 'Insulated boots for snow.',
    descriptionRu: 'Утепленные ботинки для снега.',
    effects: {},
    weight: 1.5,
    usable: true,
  },
  socks_white: {
    itemId: 'socks_white',
    name: 'Cotton Socks',
    nameRu: 'Хлопковые носки',
    category: 'clothing',
    maxStack: 1,
    icon: '🧦',
    description: 'Simple white socks.',
    descriptionRu: 'Простые белые носки.',
    effects: {},
    weight: 0.05,
    usable: true,
  },
  socks_wool: {
    itemId: 'socks_wool',
    name: 'Woolen Socks',
    nameRu: 'Шерстяные носки',
    category: 'clothing',
    maxStack: 1,
    icon: '🧦',
    description: 'Warm thick knitted socks.',
    descriptionRu: 'Теплые толстые вязаные носки.',
    effects: {},
    weight: 0.1,
    usable: true,
  },

  // HANDS
  gloves_leather: {
    itemId: 'gloves_leather',
    name: 'Leather Gloves',
    nameRu: 'Кожаные перчатки',
    category: 'clothing',
    maxStack: 1,
    icon: '🧤',
    description: 'Protects hands from cold and scratches.',
    descriptionRu: 'Защищают руки от холода и царапин.',
    effects: {},
    weight: 0.1,
    usable: true,
  },
  gloves_winter: {
    itemId: 'gloves_winter',
    name: 'Winter Gloves',
    nameRu: 'Зимние перчатки',
    category: 'clothing',
    maxStack: 1,
    icon: '🧤',
    description: 'Thick insulated gloves.',
    descriptionRu: 'Толстые утепленные перчатки.',
    effects: {},
    weight: 0.2,
    usable: true,
  },
`;

const clothingStats = `
export const CLOTHING_STATS: Record<string, import('./types').ClothingStats> = {
  beanie_black: { slot: 'head', layer: 'outerwear', insulation: 30, windResistance: 20, waterResistance: 10, breathability: 40, mobilityPenalty: 2, color: '#222' },
  cap_red: { slot: 'head', layer: 'outerwear', insulation: 5, windResistance: 5, waterResistance: 5, breathability: 60, mobilityPenalty: 0, color: '#e53e3e' },
  ushanka_hat: { slot: 'head', layer: 'outerwear', insulation: 70, windResistance: 80, waterResistance: 30, breathability: 20, mobilityPenalty: 5, color: '#5a4d41' },

  sunglasses: { slot: 'face', layer: 'outerwear', insulation: 0, windResistance: 5, waterResistance: 0, breathability: 100, mobilityPenalty: 0, color: '#111' },
  scarf_blue: { slot: 'face', layer: 'outerwear', insulation: 20, windResistance: 30, waterResistance: 10, breathability: 50, mobilityPenalty: 2, color: '#3182ce' },

  tshirt_white: { slot: 'torso', layer: 'underwear', insulation: 10, windResistance: 5, waterResistance: 0, breathability: 80, mobilityPenalty: 1, color: '#f8fafc' },
  tshirt_black: { slot: 'torso', layer: 'underwear', insulation: 10, windResistance: 5, waterResistance: 0, breathability: 80, mobilityPenalty: 1, color: '#1a202c' },
  long_johns: { slot: 'legs', layer: 'underwear', insulation: 40, windResistance: 10, waterResistance: 5, breathability: 60, mobilityPenalty: 3, color: '#e2e8f0' },

  sweater_blue: { slot: 'torso', layer: 'shirt', insulation: 45, windResistance: 15, waterResistance: 10, breathability: 40, mobilityPenalty: 5, color: '#2b6cb0' },
  plaid_shirt: { slot: 'torso', layer: 'shirt', insulation: 20, windResistance: 10, waterResistance: 5, breathability: 60, mobilityPenalty: 2, color: '#c53030', secondaryColor: '#2d3748' },

  leather_jacket: { slot: 'torso', layer: 'jacket', insulation: 30, windResistance: 90, waterResistance: 60, breathability: 15, mobilityPenalty: 10, color: '#4a3f35' },
  winter_jacket: { slot: 'torso', layer: 'jacket', insulation: 90, windResistance: 80, waterResistance: 70, breathability: 20, mobilityPenalty: 20, color: '#2b6cb0' },
  raincoat_yellow: { slot: 'torso', layer: 'outerwear', insulation: 10, windResistance: 100, waterResistance: 100, breathability: 5, mobilityPenalty: 5, color: '#ecc94b' },

  jeans_blue: { slot: 'legs', layer: 'shirt', insulation: 20, windResistance: 30, waterResistance: 10, breathability: 50, mobilityPenalty: 5, color: '#2b6cb0' },
  cargo_pants: { slot: 'legs', layer: 'shirt', insulation: 25, windResistance: 40, waterResistance: 20, breathability: 45, mobilityPenalty: 6, color: '#718096' },
  shorts_khaki: { slot: 'legs', layer: 'shirt', insulation: 5, windResistance: 5, waterResistance: 5, breathability: 90, mobilityPenalty: 0, color: '#d6bcfa' }, // wait khaki color
  
  sneakers_white: { slot: 'feet', layer: 'outerwear', insulation: 15, windResistance: 20, waterResistance: 15, breathability: 60, mobilityPenalty: 2, color: '#f8fafc' },
  work_boots: { slot: 'feet', layer: 'outerwear', insulation: 30, windResistance: 50, waterResistance: 60, breathability: 30, mobilityPenalty: 12, color: '#7b341e' },
  winter_boots: { slot: 'feet', layer: 'outerwear', insulation: 80, windResistance: 70, waterResistance: 80, breathability: 20, mobilityPenalty: 15, color: '#4a5568' },
  socks_white: { slot: 'feet', layer: 'underwear', insulation: 10, windResistance: 5, waterResistance: 0, breathability: 70, mobilityPenalty: 1, color: '#f8fafc' },
  socks_wool: { slot: 'feet', layer: 'underwear', insulation: 40, windResistance: 10, waterResistance: 10, breathability: 40, mobilityPenalty: 2, color: '#a0aec0' },

  gloves_leather: { slot: 'hands', layer: 'outerwear', insulation: 20, windResistance: 60, waterResistance: 40, breathability: 30, mobilityPenalty: 5, color: '#4a3f35' },
  gloves_winter: { slot: 'hands', layer: 'outerwear', insulation: 60, windResistance: 50, waterResistance: 50, breathability: 20, mobilityPenalty: 10, color: '#2d3748' },
};
`;

content = content.replace('litter_trash: {', clothes + '\n  litter_trash: {');
content = content.replace('export function createItem', clothingStats + '\nexport function createItem');

fs.writeFileSync('src/items.ts', content, 'utf8');
