const fs = require('fs');
let content = fs.readFileSync('src/components/CarDealershipModal.tsx', 'utf8');

const newArray = `export const DEALERSHIP_CARS: DealershipCarModel[] = [
  {
    id: 'deal_sedan_classic',
    type: 'sedan_classic',
    name: 'Классический седан',
    nameRu: 'Классический седан',
    brand: 'Автомобиль',
    classType: 'Седан',
    year: 1992,
    engineSpec: '1.6L 8V Карбюратор',
    powerHp: 75,
    displacementL: 1.6,
    fuelType: 'ai92',
    fuelTypeLabel: 'АИ-92',
    topSpeedKmh: 150,
    accelSec: 16.0,
    weightKg: 1045,
    tankCapacityL: 39,
    dimensionsM: '4.1 x 1.61 м',
    hasAutoTrans: false,
    hasManualTrans: true,
    priceRub: 180000,
    availableColors: [
      { name: 'Белый (201)', hex: '#e2e8f0' },
      { name: 'Рубин', hex: '#991b1b' },
      { name: 'Океан', hex: '#1e3a8a' },
      { name: 'Сафари', hex: '#fcd34d' }
    ],
    descriptionRu: 'Надежная проверенная временем классика. Задний привод, простая конструкция.'
  },
  {
    id: 'deal_classic_compact',
    type: 'classic_compact',
    name: 'Классический Жук',
    nameRu: 'Классический Жук',
    brand: 'Автомобиль',
    classType: 'Компакт',
    year: 1978,
    engineSpec: '1.2L 8V Карбюратор',
    powerHp: 64,
    displacementL: 1.2,
    fuelType: 'ai92',
    fuelTypeLabel: 'АИ-92',
    topSpeedKmh: 140,
    accelSec: 20.0,
    weightKg: 955,
    tankCapacityL: 39,
    dimensionsM: '4.0 x 1.61 м',
    hasAutoTrans: false,
    hasManualTrans: true,
    priceRub: 150000,
    availableColors: [
      { name: 'Светло-желтый', hex: '#fef08a' },
      { name: 'Голубой', hex: '#7dd3fc' },
      { name: 'Вишневый', hex: '#7f1d1d' }
    ],
    descriptionRu: 'Легкий и экономичный классический автомобиль с узнаваемым дизайном.'
  },
  {
    id: 'deal_wagon_classic',
    type: 'wagon_classic',
    name: 'Универсал 80-х',
    nameRu: 'Универсал 80-х',
    brand: 'Автомобиль',
    classType: 'Универсал',
    year: 1999,
    engineSpec: '1.5L 8V Карбюратор',
    powerHp: 71,
    displacementL: 1.5,
    fuelType: 'ai92',
    fuelTypeLabel: 'АИ-92',
    topSpeedKmh: 145,
    accelSec: 18.0,
    weightKg: 1060,
    tankCapacityL: 45,
    dimensionsM: '4.1 x 1.62 м',
    hasAutoTrans: false,
    hasManualTrans: true,
    priceRub: 210000,
    availableColors: [
      { name: 'Белый', hex: '#f8fafc' },
      { name: 'Баклажан', hex: '#4c1d95' },
      { name: 'Мурена', hex: '#134e4a' }
    ],
    descriptionRu: 'Вместительный и практичный универсал для перевозки грузов.'
  },
  {
    id: 'deal_suv_classic_box',
    type: 'suv_classic_box',
    name: 'Рамный Внедорожник',
    nameRu: 'Рамный Внедорожник',
    brand: 'Внедорожник',
    classType: 'Рамный внедорожник',
    year: 1985,
    engineSpec: '2.4L Карбюратор',
    powerHp: 75,
    displacementL: 2.4,
    fuelType: 'ai92',
    fuelTypeLabel: 'АИ-92',
    topSpeedKmh: 110,
    accelSec: 25.0,
    weightKg: 1650,
    tankCapacityL: 78,
    dimensionsM: '4.0 x 1.78 м',
    hasAutoTrans: false,
    hasManualTrans: true,
    priceRub: 350000,
    availableColors: [
      { name: 'Хаки', hex: '#4d7c0f' },
      { name: 'Серый', hex: '#64748b' }
    ],
    descriptionRu: 'Бескомпромиссный рамный внедорожник для тяжелого бездорожья.'
  },
  {
    id: 'deal_van_cargo_old',
    type: 'van_cargo_old',
    name: 'Старый фургон',
    nameRu: 'Старый фургон',
    brand: 'Фургон',
    classType: 'Микроавтобус 4x4',
    year: 2010,
    engineSpec: '2.7L Инжектор',
    powerHp: 112,
    displacementL: 2.7,
    fuelType: 'ai92',
    fuelTypeLabel: 'АИ-92',
    topSpeedKmh: 120,
    accelSec: 22.0,
    weightKg: 1900,
    tankCapacityL: 77,
    dimensionsM: '4.3 x 1.94 м',
    hasAutoTrans: false,
    hasManualTrans: true,
    priceRub: 420000,
    availableColors: [
      { name: 'Защитный', hex: '#3f6212' },
      { name: 'Белая Ночь', hex: '#cbd5e1' }
    ],
    descriptionRu: 'Незаменимый помощник в труднодоступных районах и на плохих дорогах.'
  },
  {
    id: 'deal_mtz80',
    type: 'tractor_mtz80',
    name: 'МТЗ-80 «Беларус» (4x2)',
    nameRu: 'МТЗ-80 «Беларус» (4x2)',
    brand: 'Спецтехника',
    classType: 'Трактор',
    year: 1995,
    engineSpec: '4.75L Дизель',
    powerHp: 80,
    displacementL: 4.75,
    fuelType: 'diesel',
    fuelTypeLabel: 'ДТ',
    topSpeedKmh: 35,
    accelSec: 15.0,
    weightKg: 3770,
    tankCapacityL: 130,
    dimensionsM: '3.8 x 1.97 м',
    hasAutoTrans: false,
    hasManualTrans: true,
    priceRub: 850000,
    availableColors: [
      { name: 'Тракторный красный', hex: '#dc2626' },
      { name: 'Синий', hex: '#2563eb' }
    ],
    descriptionRu: 'Универсально-пропашной трактор.'
  },
  {
    id: 'deal_izh_jupiter',
    type: 'moto_izh_jupiter',
    name: 'Иж Юпитер-5',
    nameRu: 'Иж Юпитер-5',
    brand: 'Мотоцикл',
    classType: 'Классический мотоцикл',
    year: 1990,
    engineSpec: '347cc 2-тактный',
    powerHp: 24,
    displacementL: 0.35,
    fuelType: 'ai92',
    fuelTypeLabel: 'АИ-92 (Смесь)',
    topSpeedKmh: 125,
    accelSec: 9.0,
    weightKg: 160,
    tankCapacityL: 18,
    dimensionsM: '2.1 x 0.8 м',
    hasAutoTrans: false,
    hasManualTrans: true,
    priceRub: 55000,
    availableColors: [
      { name: 'Голубой', hex: '#38bdf8' },
      { name: 'Красный', hex: '#ef4444' }
    ],
    descriptionRu: 'Популярный дорожный мотоцикл среднего класса.'
  },
  {
    id: 'deal_ural',
    type: 'moto_ural_sidecar',
    name: 'Урал М-67 с коляской',
    nameRu: 'Урал М-67 с коляской',
    brand: 'Мотоцикл',
    classType: 'Мотоцикл с коляской',
    year: 1982,
    engineSpec: '649cc Оппозитный',
    powerHp: 32,
    displacementL: 0.65,
    fuelType: 'ai92',
    fuelTypeLabel: 'АИ-92',
    topSpeedKmh: 105,
    accelSec: 12.0,
    weightKg: 330,
    tankCapacityL: 19,
    dimensionsM: '2.4 x 1.6 м',
    hasAutoTrans: false,
    hasManualTrans: true,
    priceRub: 95000,
    availableColors: [
      { name: 'Темно-зеленый', hex: '#14532d' },
      { name: 'Черный', hex: '#171717' }
    ],
    descriptionRu: 'Тяжелый мотоцикл с боковым прицепом.'
  }
];`;

const startIdx = content.indexOf('export const DEALERSHIP_CARS');
const endIdx = content.indexOf('];', startIdx) + 2;

content = content.substring(0, startIdx) + newArray + content.substring(endIdx);
fs.writeFileSync('src/components/CarDealershipModal.tsx', content);
