import { GameWorld, GuardrailSegment } from './types';

/**
 * Creates and initializes realistic soft guardrails with impact attenuators (ударогасители)
 * along divided highway M-12, hazardous verges, and bridges, with zero blocked turnoffs.
 */
export function ensureWorldGuardrails(world: GameWorld): GuardrailSegment[] {
  if (world.guardrails && world.guardrails.length > 0) {
    return world.guardrails;
  }

  const guardrails: GuardrailSegment[] = [
    // =========================================================================
    // 1. STEPPE HIGHWAY M-12 - MEDIAN BARRIERS (Разделительный брус М-12 y=4000)
    // =========================================================================
    // Segment 1A: City Gate (8140) to Station/Village Crossover (11020)
    {
      id: 'm12_median_seg_1a',
      x1: 8140,
      y1: 4000,
      x2: 11020,
      y2: 4000,
      width: 6,
      type: 'double_w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 32,
      endAttenuatorLength: 32,
      deformations: [],
      isSideBarrier: false,
    },
    // Segment 1B: Station/Village Crossover (11480) to Hub 1 (14280)
    {
      id: 'm12_median_seg_1b',
      x1: 11480,
      y1: 4000,
      x2: 14280,
      y2: 4000,
      width: 6,
      type: 'double_w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 32,
      endAttenuatorLength: 32,
      deformations: [],
      isSideBarrier: false,
    },
    // Segment 2: Hub 1 (14550) to Hub 2 (23850)
    {
      id: 'm12_median_seg_2',
      x1: 14550,
      y1: 4000,
      x2: 23850,
      y2: 4000,
      width: 6,
      type: 'double_w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 32,
      endAttenuatorLength: 32,
      deformations: [],
      isSideBarrier: false,
    },
    // Segment 3: Hub 2 (24150) to Hub 3 (35850)
    {
      id: 'm12_median_seg_3',
      x1: 24150,
      y1: 4000,
      x2: 35850,
      y2: 4000,
      width: 6,
      type: 'double_w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 32,
      endAttenuatorLength: 32,
      deformations: [],
      isSideBarrier: false,
    },
    // Segment 4: Hub 3 (36150) to Hub 4 (47850)
    {
      id: 'm12_median_seg_4',
      x1: 36150,
      y1: 4000,
      x2: 47850,
      y2: 4000,
      width: 6,
      type: 'double_w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 32,
      endAttenuatorLength: 32,
      deformations: [],
      isSideBarrier: false,
    },

    // =========================================================================
    // 2. STEPPE HIGHWAY M-12 - NORTH SHOULDER BARRIERS (Северные обочинные отбойники y=3904)
    // Clear openings provided for Forest Firebreak #1 (10400), Polynovka Village (11400), and Forest Firebreak #2 (14200)
    // =========================================================================
    {
      id: 'm12_north_shoulder_1a',
      x1: 8140,
      y1: 3904,
      x2: 10340,
      y2: 3904,
      width: 5,
      type: 'w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 28,
      endAttenuatorLength: 28,
      deformations: [],
      isSideBarrier: true,
    },
    {
      id: 'm12_north_shoulder_1b',
      x1: 10460,
      y1: 3904,
      x2: 11330,
      y2: 3904,
      width: 5,
      type: 'w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 28,
      endAttenuatorLength: 28,
      deformations: [],
      isSideBarrier: true,
    },
    {
      id: 'm12_north_shoulder_1c',
      x1: 11470,
      y1: 3904,
      x2: 14130,
      y2: 3904,
      width: 5,
      type: 'w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 28,
      endAttenuatorLength: 28,
      deformations: [],
      isSideBarrier: true,
    },
    {
      id: 'm12_north_shoulder_2',
      x1: 14550,
      y1: 3904,
      x2: 23850,
      y2: 3904,
      width: 5,
      type: 'w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 32,
      endAttenuatorLength: 32,
      deformations: [],
      isSideBarrier: true,
    },
    {
      id: 'm12_north_shoulder_3',
      x1: 24150,
      y1: 3904,
      x2: 35850,
      y2: 3904,
      width: 5,
      type: 'w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 32,
      endAttenuatorLength: 32,
      deformations: [],
      isSideBarrier: true,
    },
    {
      id: 'm12_north_shoulder_4',
      x1: 36150,
      y1: 3904,
      x2: 47850,
      y2: 3904,
      width: 5,
      type: 'w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 32,
      endAttenuatorLength: 32,
      deformations: [],
      isSideBarrier: true,
    },

    // =========================================================================
    // 3. STEPPE HIGHWAY M-12 - SOUTH SHOULDER BARRIERS (Южные обочинные отбойники y=4096)
    // Clear opening provided for Railway Station Access Highway (11110/11280)
    // =========================================================================
    {
      id: 'm12_south_shoulder_1a',
      x1: 8140,
      y1: 4096,
      x2: 11020,
      y2: 4096,
      width: 5,
      type: 'w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 28,
      endAttenuatorLength: 28,
      deformations: [],
      isSideBarrier: true,
    },
    {
      id: 'm12_south_shoulder_1b',
      x1: 11360,
      y1: 4096,
      x2: 14280,
      y2: 4096,
      width: 5,
      type: 'w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 28,
      endAttenuatorLength: 28,
      deformations: [],
      isSideBarrier: true,
    },
    {
      id: 'm12_south_shoulder_2',
      x1: 14550,
      y1: 4096,
      x2: 23850,
      y2: 4096,
      width: 5,
      type: 'w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 32,
      endAttenuatorLength: 32,
      deformations: [],
      isSideBarrier: true,
    },
    {
      id: 'm12_south_shoulder_3',
      x1: 24150,
      y1: 4096,
      x2: 35850,
      y2: 4096,
      width: 5,
      type: 'w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 32,
      endAttenuatorLength: 32,
      deformations: [],
      isSideBarrier: true,
    },
    {
      id: 'm12_south_shoulder_4',
      x1: 36150,
      y1: 4096,
      x2: 47850,
      y2: 4096,
      width: 5,
      type: 'w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 32,
      endAttenuatorLength: 32,
      deformations: [],
      isSideBarrier: true,
    },

    // =========================================================================
    // 4. RIVER BRIDGES PROTECTIVE SIDE BARRIERS (Защитные мостовые ограждения)
    // Real bridge side barriers at logging river crossing (y = -3360..-3240)
    // =========================================================================
    {
      id: 'bridge_logging_west',
      x1: 9370,
      y1: -3360,
      x2: 9370,
      y2: -3240,
      width: 5,
      type: 'w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 20,
      endAttenuatorLength: 20,
      deformations: [],
      isSideBarrier: true,
    },
    {
      id: 'bridge_logging_east',
      x1: 9430,
      y1: -3360,
      x2: 9430,
      y2: -3240,
      width: 5,
      type: 'w_beam',
      hasStartAttenuator: true,
      hasEndAttenuator: true,
      startAttenuatorCompression: 0,
      endAttenuatorCompression: 0,
      startAttenuatorLength: 20,
      endAttenuatorLength: 20,
      deformations: [],
      isSideBarrier: true,
    },
  ];

  world.guardrails = guardrails;
  return guardrails;
}
